### ISSUE TITLE
[Bug] bufr2ioda fails with multiple subsets in a bufr file (e.g. NSST)

### ISSUE THREAD

**Issue by ShastriPaturi** [JCSDA-internal/ioda-converters#1139]
## Current behavior (describe the bug)
>bufr2ioda fails with multiple subsets in a bufr file (e.g. NSST)

An example of the yaml is attached:

```yaml
observations:
  - obs space:
      name: bufr
      obsdatain: "./gdas.t06z.nsstbufr"

      exports:
        #group_by_variable: depth  # Optional
        variables:
          timestamp:
            datetime:
              year: "*/YEAR[1]"
              month: "*/MNTH[1]"
              day: "*/DAYS[1]"
              hour: "*/HOUR[1]"
              minute: "*/MINU[1]"

          rcptimestamp:
            datetime:
              year: "*/RCPTIM/RCYR"
              month: "*/RCPTIM/RCMO"
              day: "*/RCPTIM/RCDY"
              hour: "*/RCPTIM/RCHR"
              minute: "*/RCPTIM/RCMI"

          longitude:
            query: "*/CLON"
          latitude:
            query: "*/CLAT"
```

The following error is generated when running bufr2ioda:
PRE-MAIN-WARNING Warning: Query String */RCPTIM/RCYR didn't apply to subset NC031002
PRE-MAIN-WARNING Warning: Query String */CLON didn't apply to subset NC031002
PRE-MAIN-WARNING Warning: Query String */RCPTIM/RCDY didn't apply to subset NC031002
PRE-MAIN-WARNING Warning: Query String */RCPTIM/RCMI didn't apply to subset NC031002
PRE-MAIN-WARNING Warning: Query String */SST1 didn't apply to subset NC031002
PRE-MAIN-WARNING Warning: Query String */RCPTIM/RCHR didn't apply to subset NC031002
PRE-MAIN-WARNING Warning: Query String */YEAR[1] didn't apply to subset NC031002
PRE-MAIN-WARNING Warning: Query String */DAYS[1] didn't apply to subset NC031002
**terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append**
