### ISSUE TITLE
BufrConverter: Value transform from lookup table data.

### ISSUE THREAD

**Issue by rmclaren** [JCSDA-internal/ioda-converters#377]
Investigate the possibility of adding an export transform to BufrParser that can convert BUFR mnemonic numbers (for example: scan  angles) to their actual values. In bufr these values are often represented as integer numbers (0-50 say) and then are later converted to actual angle values...

You can already kind of handle this if you are willing to hard coded values in the YAML file by using export transforms as in the following example:

```
exports:
  scanangle:
    mnemonic: BEARAZ
    transforms:
      - scale: 1.13
      - offset: -48.90

```
Where 1.13 is the resolution and -48.90 is the offset where BEARAZ values are 0 (equivalent to values*1.13 + -48.90).

This is a complicated question as it brings up the issue of meta data management. Currently the parameters for different platforms are stored in separate text files...
