### ISSUE TITLE
BufrConverter: Add ability to declare specify subset ID in YAML config.

### ISSUE THREAD

**Issue by rmclaren** [JCSDA-internal/ioda-converters#385]
Add ability to specify subset ID's and what mnemonics to parse from each one. I'm thinking of following the following example (need feedback):

```
    bufr:
      <...>

      dataSets:
        - subsets:
            pattern: NC02102[123]  # optional regex pattern: if missing apply this to all subsets not otherwise 
                                                  # mentioned (becomes default)
            mnemonicSets:
              - mnemonics: [ SAID, FOVN, YEAR, MNTH, DAYS, HOUR, MINU, SECO, CLAT, CLON, HOLS ]
              - mnemonics: [ SAZA, SOZA, BEARAZ, SOLAZI ]
              - mnemonics: [ TMBR ]
                indicies : 1-5         # changed to something more generic than "channels".
        - subsets:
            pattern: NC021024[67]
            mnemonicSets:
              - mnemonics: [ SAID, FOVN, YEAR, MNTH, DAYS, HOUR, MINU, SECO, CLATH, CLONH, HOLS ]
              - mnemonics: [ SAZA, SOZA, BEARAZ, SOLAZI ]
              - mnemonics: [ TMBR ]
                indicies: 1-15        # changed to something more generic than "channels"
        <...>

      exports:
        variables:
          latitude:
            mnemonic: [CLAT, CLATH]   # picks the one thats valid (is not BUFR invalid number). 
                                                          # Runtime error if both invalid.
          radiance:
            mnemonic: [ TMBR ]
        <...>

    ioda:
      backend: netcdf
      obsdataout: "./testrun/gdas.t18z.{subset.id}.tm00.nc"  # subset name substituted for {subset}

      <...>
```
