### ISSUE TITLE
Test and Enhance BUFR-to-IODA YAML for MHS

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#423]
## Description

**Complete YAML file that maps the BUFR Mnenomics to Unified IODA Names for MHS (ATOVS)**

**Branch** - [feature/bufr2ioda_mhs](https://github.com/JCSDA-internal/ioda-converters/tree/feature/bufr2ioda_mhs)

**To-do list**
- [x] Complete YAML for MHS
- [x] Run BUFR2IODA and verify consistency between BUFR and IODA

**Resources**
[NOAA NCEP BUFR Table 021](https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/decoders/decod_shared/fix/bufrtab.021)
[read_bufrtovs.f90](https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/global_shared.v14.1.7/sorc/gsi.fd/read_bufrtovs.f90)

---

*(Instructions: replace text in this and all sections with your own text)*

Provide a detailed description of this issue.

What problem needs to be fixed? What new capability needs to be added?

If this is a bug, describe the current behavior.

[Be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## Requirements

If this is a new feature: What does the new code need to accomplish? Does it require new software dependencies (e.g. new jedi-stack components or new python modules?)

If this is a bugfix: What is the expected behavior?

## Acceptance Criteria (Definition of Done)

What does it mean for this to be finished?

## Dependencies

What must be done before this can be done?
 - add issue dependencies in ZenHub as appropriate

Does this block progress on other issues?
 - add this issue as a dependency to other ZenHub issues as appropriate

**Comment by emilyhcliu** [comment]
```
# (C) Copyright 2020 NOAA/NWS/NCEP/EMC
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.

observations:
  - obs space:
      name: bufr
      obsdatain: "./testinput/gdas.t12z.1bmhs.tm00.bufr_d"
      mnemonicSets:
        - mnemonics: [SAID, FOVN, YEAR, MNTH, DAYS, HOUR, MINU, SECO, CLAT, CLON, CLATH, CLONH, HOLS]
        - mnemonics: [SAZA, SOZA, BEARAZ, SOLAZI]
        - mnemonics: [TMBR]
          channels : 1-5

      exports:
        splits:
          satId:
            category:
              mnemonic: SAID
              map:
                _3: metop-b
                _4: metop-a
                _5: metop-c
                _223: noaa-19

        variables:
          timestamp:
            datetime:
              year: YEAR
              month: MNTH
              day: DAYS
              hour: HOUR
              minute: MINU
              second: SECO

          longitude:
            mnemonic: CLON

          latitude:
            mnemonic: CLAT

          satelliteIdentifier:
            mnemonic: SAID

          satelliteZenithAngle:
            mnemonic: SAZA

          satelliteAzimuthAngle:
            mnemonic: BEARAZ

          solarZenithAngle:
            mnemonic: SOZA

          solarAzimuthAngle:
            mnemonic: SOLAZI

          heightOfSurface:
            mnemonic: HOLS

          sensorScanPosition:
            mnemonic: FOVN

          brightnessTemperature:
            mnemonic: TMBR

    ioda:
      backend: netcdf
      obsdataout: "./testrun/gdas.t12z.1bmhs.tm00.{splits/satId}.nc"
#     obsdataout: "./testrun/gdas.t12z.1bmhs.tm00.nc"

      dimensions:
        - name: "nlocs"
          size: variables/brightnessTemperature.nrows
        - name: "nchans"
          size: variables/brightnessTemperature.ncols

      variables:
        - name: "datetime@MetaData"
          source: variables/timestamp
          dimensions: [ "nlocs" ]
          longName: "Datetime"
          units: "datetime"

        - name: "latitude@MetaData"
          source: variables/latitude
          dimensions: ["nlocs"]
          longName: "Latitude"
          units: "degrees_north"
          range: [-90, 90]

        - name: "longitude@MetaData"
          source: variables/longitude
          dimensions: ["nlocs"]
          longName: "Longitude"
          units: "degrees_east"
          range: [-180, 180]

        - name: "satelliteIdentifier@MetaData"
          source: "variables/satelliteIdentifier"
          dimensions: ["nlocs"]
          longName: "Satellite Identifier"
          units: "None"

        - name: "sensorZenithAngle@MetaData"
          source: "variables/satelliteZenithAngle"
          dimensions: ["nlocs"]
          longName: "Satellite Zenith Angle"
          units: "degrees"
          range: [0, 90]

        - name: "sensorAzimuthAngle@MetaData"
          source: "variables/satelliteAzimuthAngle"
          dimensions: ["nlocs"]
          longName: "Satellite Azimuth Angle"
          units: "degrees_true"
          range: [0, 360]

        - name: "solarZenithAngle@MetaData"
          source: "variables/solarZenithAngle"
          dimensions: ["nlocs"]
          longName: "Solar Zenith Angle"
          units: "degrees"
          range: [0, 180]

        - name: "solarAzimuthAngle@MetaData"
          source: "variables/solarAzimuthAngle"
          dimensions: ["nlocs"]
          longName: "Solar Zenith Angle"
          units: "degrees_true"
          range: [0, 360]
        - name: "heightOfSurface@MetaData"
          source: "variables/heightOfSurface"
          dimensions: ["nlocs"]
          longName: "Height of Land Surface"
          units: "meter"

        - name: "sensorScanPosition@MetaData"
          source: "variables/sensorScanPosition"
          dimensions: ["nlocs"]
          longName: "Field of View Number"
          units: "None"
          range: [1, 90]

        - name: "brightnessTemperature@ObsValue"
          coordinates: "longitude latitude nchans"
          source: variables/brightnessTemperature
          dimensions: ["nlocs", "nchans"]
          longName: "Brightness Temperature"
          units: "K"
          range: [120, 500]
          chunks: [1000, 15]
          compressionLevel: 4
```
