### ISSUE TITLE
bufr2ioda: Print out a helpful message when a dimension name is specified incorrectly compared to expected, such as a typo in spelling in 1 of 2 places

### ISSUE THREAD

**Issue by gthompsnJCSDA** [JCSDA-internal/ioda-converters#488]
## Description

A somewhat not useful std::out_of_bounds error message occurs when a dimension name is set in one part of the yaml, but then mismatched due to a typo in the variable name list export.  Example shown via these yaml snippets...

```
      dimensions:
        - name: "nchans_abledo"
          size: variables/albedo.ncols

        - name: "albedo@ObsValue"
          coordinates: "longitude latitude nchans"
          source: variables/albedo
          dimensions: ["nlocs", "nchans_albedo"]

```

Note the spelling typo `abledo` is the incorrect one and just catching a mismatch with a more useful print/debug would be very helpful to diagnose this type of problem in an otherwise large yaml.

## Acceptance Criteria (Definition of Done)

Enhancement for debug printing rather than aborting with out_of_range error.

## Dependencies

No dependencies
