### ISSUE TITLE
feature/query_cxx_types --- bug found when query variable with different precision

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#976]
## Current behavior (describe the bug)

When query a BUFR variable with mixed precision, the process will be terminated with errors.

Example:  
```
          latitude:
            query: "[*/CLAT, */CLATH]"
          longitude:
            query: "[*/CLON, */CLONH]"

```
While executing query for variable with the different precision, the process will be terminated with the following error message:
```
PRE-MAIN-ERROR Exception: Bad parameter: Different subsets units don't agree for field latitude. DEGREES vs DEGREE(N+,S-)N 
terminate called after throwing an instance of 'eckit::BadParameter'
  what():  Bad parameter: Different subsets units don't agree for field latitude. DEGREES vs DEGREE(N+,S-)N


```

This case can be reproduced using [bufr_ncep_adpsfc.yaml](https://github.com/JCSDA-internal/ioda-converters/blob/feature/query_cxx/test/testinput/bufr_ncep_adpsfc.yaml)
